// Storyloom's legal documents: one source for the TV app, the phone and the website.
// Written in plain language on purpose. The English version is the one that applies.

export const LEGAL_VERSION = '2026-09-25';
export const LEGAL_UPDATED = '25 September 2026';

/**
 * Who families can contact about privacy, safety or these terms. Messages sent from
 * "Help & contact" (TV, phone or website) go straight to the Storyloom team.
 * Add a public email address here before a store launch.
 */
export const LEGAL_CONTACT = {
  owner: 'Bapan Ghosh and Jayashree Mondal',
  officer: 'Bapan Ghosh',
  channel: 'the Help & contact form (in the app under Settings → Help & contact, or on our website)',
  country: 'India',
};

export interface LegalSection {
  heading: string;
  body: string[]; // paragraphs; lines starting with "• " are bullet points
}

export interface LegalDocument {
  id: 'terms' | 'privacy' | 'children';
  title: string;
  summary: string[];
  sections: LegalSection[];
}

const C = LEGAL_CONTACT;

export const TERMS: LegalDocument = {
  id: 'terms',
  title: 'Terms of Service',
  summary: [
    'Storyloom is for families. A grown-up (18+) creates the account and supervises children.',
    'Stories are made with AI. We add strong safety checks, but no filter is perfect, so please watch together.',
    'Your drawings, ideas and stories stay yours. We only use them to make your family’s stories.',
    'Be kind: no harmful, illegal or hateful content, and no attempts to get around the safety checks.',
    'You can delete your account and everything in it at any time.',
  ],
  sections: [
    {
      heading: '1. About these terms',
      body: [
        `These Terms of Service (“Terms”) are an agreement between you and Storyloom, created and run by ${C.owner} (“Storyloom”, “we”, “us”). They apply to the Storyloom apps for TVs (including Amazon Fire TV), the Storyloom phone companion, our website and every related service (together, the “Service”).`,
        'By creating an account, signing in, or using the Service, you agree to these Terms and to our Privacy Policy and Children’s Privacy Notice. If you do not agree, please do not use the Service.',
        `Version ${LEGAL_VERSION}. We show you what changed whenever these Terms change in an important way, and we ask you to accept them again.`,
      ],
    },
    {
      heading: '2. Who can use Storyloom',
      body: [
        '• Accounts are for adults. You must be at least 18 years old (or the age of majority where you live) and able to enter a binding contract to create an account.',
        '• Children may enjoy Storyloom only with the permission and supervision of a parent or legal guardian who holds the account. By adding a child profile, you confirm that you are that child’s parent or legal guardian, or have their permission, and you consent to the processing described in our Children’s Privacy Notice.',
        '• You may not use the Service if you are barred from doing so under the laws that apply to you.',
      ],
    },
    {
      heading: '3. Your account',
      body: [
        '• We verify accounts with a one-time code sent to your mobile number. Keep your phone and codes private; never share a sign-in code with anyone, including anyone claiming to be from Storyloom.',
        '• You are responsible for activity on your account and on TVs you sign in. Use “Sign out of all devices” in Settings if you think someone else has access.',
        '• Please give accurate information and keep it up to date. One account can hold one family with several child profiles.',
        '• A TV can be signed in by scanning a code with your phone. Only approve codes shown on your own TV.',
      ],
    },
    {
      heading: '4. What the Service does',
      body: [
        'Storyloom lets a family create illustrated, narrated stories together: phones add a hero (for example a child’s drawing), a world and a twist, and the TV turns them into a story. The Service uses cloud computing and artificial intelligence (“AI”) provided by Amazon Web Services to write, check, illustrate and narrate stories.',
        'We work hard to keep the Service available, fast and safe, but we may change, pause or stop features, and we cannot promise it will always be available or error-free. Some features are marked as previews and may change.',
      ],
    },
    {
      heading: '5. AI-generated stories and safety',
      body: [
        '• Stories, pictures and voices are generated by AI. They are fiction. They may contain mistakes, odd details or ideas you do not expect. Educational facts in stories are simplified and may not be complete.',
        '• Every idea and every story passes automated safety checks designed for children (including content filters for violence, fear, hate, sexual content and personal information), and parents can choose gentler settings. These checks greatly reduce risk but cannot guarantee that every result will suit every child.',
        '• A grown-up should stay nearby, especially with younger children. If something seems wrong, stop the story and use “Report a problem” so we can improve.',
        '• Storyloom is entertainment. It is not a substitute for parenting, education, therapy, medical or professional advice.',
      ],
    },
    {
      heading: '6. Your content',
      body: [
        '“Your Content” means what you and your family add: drawings and photos of drawings, names, ideas typed or spoken on a phone, votes and choices, and the settings you choose.',
        '• You keep ownership of Your Content. You give us a limited, worldwide, non-exclusive, royalty-free licence to host, process, copy and adapt Your Content only to provide and secure the Service for you (for example to turn a drawing into a hero, to store your bookshelf, and to run safety checks). This licence ends when you delete the content or your account, except for copies we must keep for a short time for security, backups or the law.',
        '• Please only upload drawings you or your family made. Do not upload photos of people’s faces, other people’s personal information, or material you do not have the right to use.',
        '• By default, photos of drawings are deleted automatically within 24 hours; only the illustrated hero is kept with your story. You can change this in Settings.',
      ],
    },
    {
      heading: '7. Stories you create',
      body: [
        'Subject to these Terms and to the rights of others, you may keep, re-read, share with family and friends and print the stories your family creates for personal, non-commercial purposes. We do not claim ownership of your stories. Because AI can produce similar results for different people, we cannot promise that a story or picture is unique, and some countries do not give copyright protection to AI-generated material.',
      ],
    },
    {
      heading: '8. Acceptable use',
      body: [
        'You agree not to, and not to let anyone else:',
        '• create, upload or request content that is illegal, sexual, hateful, harassing, violent, dangerous, or that exploits or endangers children in any way;',
        '• try to get around, test or disable safety checks, parental controls, rate limits or security measures (unless you are taking part in our authorised security programme);',
        '• share other people’s personal information, or impersonate anyone;',
        '• copy, scrape, resell, sublicense or commercially exploit the Service, or use it to build a competing product or to train AI models;',
        '• reverse engineer the apps, except where the law allows it despite this restriction;',
        '• interfere with the Service or other families, including by sending malware, spam or excessive automated requests.',
        'We may remove content, limit features or suspend accounts that break these rules. We report suspected child sexual abuse material and credible threats to the authorities as the law requires.',
      ],
    },
    {
      heading: '9. Price',
      body: [
        'Storyloom is currently free. Fair-use limits apply (for example, a daily number of new stories per family) to keep the Service fast and affordable for everyone. If we ever offer paid features, we will show the price clearly and ask for your agreement before you are charged. There are no ads in Storyloom and no in-app purchases for children.',
      ],
    },
    {
      heading: '10. Other companies’ services',
      body: [
        'The Service runs on Amazon Web Services and works with devices and services such as Amazon Fire TV, Alexa voice commands, mobile networks and your phone’s browser. Those companies’ own terms and privacy notices also apply to your use of their products. We are not responsible for their services.',
      ],
    },
    {
      heading: '11. Our rights',
      body: [
        'The Service, including its software, design, logo, name, music, sounds, sky animations and other material we create (but not Your Content), belongs to us or our licensors and is protected by law. We give you a personal, revocable, non-exclusive, non-transferable licence to use the apps for as long as you follow these Terms. Open-source components are licensed under their own licences, listed in Settings → About. If you send us feedback or ideas, we may use them without any obligation to you.',
      ],
    },
    {
      heading: '12. Ending your use',
      body: [
        'You can stop using Storyloom at any time and delete your account in Settings → Account → Delete account; this deletes your family’s stories, pictures and profiles as described in the Privacy Policy. We may suspend or close accounts that seriously or repeatedly break these Terms, that create risk for children or others, or where the law requires it. Where appropriate we will tell you why and give you a chance to respond. Sections 6, 7, 11, 13, 14, 15 and 16 continue after your account ends.',
      ],
    },
    {
      heading: '13. Disclaimers',
      body: [
        'To the fullest extent the law allows, the Service is provided “as is” and “as available”, without warranties of any kind, whether express or implied, including warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy or uninterrupted availability. Nothing in these Terms limits rights you have as a consumer that cannot be limited by contract.',
      ],
    },
    {
      heading: '14. Limitation of liability',
      body: [
        'To the fullest extent the law allows: (a) we are not liable for indirect, incidental, special, consequential or punitive damages, or for loss of data, profits or goodwill; and (b) our total liability for all claims about the Service is limited to the greater of the amount you paid us in the 12 months before the claim (if any) or INR 5,000 (or the equivalent in your currency).',
        'We do not exclude or limit liability for death or personal injury caused by negligence, for fraud, or for anything else that cannot be excluded or limited under the law that applies to you.',
      ],
    },
    {
      heading: '15. Responsibility for misuse',
      body: [
        'If you break these Terms or the law, or misuse the Service, you are responsible for the resulting claims and costs brought by others against us, to the extent the law allows. This does not apply to consumers where such a promise is not allowed.',
      ],
    },
    {
      heading: '16. Law and disputes',
      body: [
        `These Terms are governed by the laws of ${C.country}, without regard to conflict-of-law rules. Please contact us first; most concerns can be solved quickly and informally. If we cannot resolve a dispute within 30 days, the courts of ${C.country} will have jurisdiction. If you live in another country, you keep the protection of the mandatory consumer laws of that country and may bring a claim in your local courts.`,
      ],
    },
    {
      heading: '17. Changes to these Terms',
      body: [
        'We may update these Terms to reflect changes to the Service or the law. For important changes we will notify you in the app at least 14 days in advance (unless the change is urgently needed for safety or legal reasons) and ask you to accept the new version. If you do not agree, you can delete your account before the changes take effect.',
      ],
    },
    {
      heading: '18. Contact',
      body: [`Questions about these Terms? Write to us through ${C.channel}. Storyloom is created by ${C.owner}, ${C.country}.`],
    },
  ],
};

export const PRIVACY: LegalDocument = {
  id: 'privacy',
  title: 'Privacy Policy',
  summary: [
    'We collect as little as possible, and only to make your family’s stories.',
    'We never store your phone number: we keep a secure fingerprint of it and the last two digits.',
    'Drawings are deleted within 24 hours unless you choose to keep them.',
    'No ads, no selling or sharing of data for advertising, no tracking across apps, no location, and the TV never records audio.',
    'See, download or delete your data at any time in Settings.',
  ],
  sections: [
    {
      heading: '1. Who we are',
      body: [
        `Storyloom is created by ${C.owner} (${C.country}). We are the “data controller” (or “data fiduciary”) for the personal data described here. Contact us through ${C.channel}. Grievance and privacy contact: ${C.officer}.`,
      ],
    },
    {
      heading: '2. What we collect',
      body: [
        'Account information (from the grown-up):',
        '• Mobile number, used only to send a one-time sign-in code. We keep a keyed, one-way fingerprint of the number (so we can recognise your account next time) and its last two digits for display. We do not store the full number.',
        '• Your name, the role you choose (parent, guardian, grandparent, teacher), your country and language, and an email address if you choose to give one.',
        '• The date and version of the terms you accepted.',
        'Family and story information:',
        '• For each child profile: a first name or nickname, an age range (such as 6–8), and a picture chosen from our animal avatars. We do not ask for a child’s date of birth, photo, school or contact details.',
        '• What the family adds to a story: drawing photos, hero names, story ideas and choices. Ideas spoken on a phone are turned into text by the phone’s own speech feature; we receive only the text, never the recording.',
        '• The stories we create for you (text, pictures, narration) and your bookshelf.',
        'Device and technical information:',
        '• A random household ID for each TV, secure sign-in tokens, and your app settings.',
        '• Limited service logs (time, request type, error codes) and your IP address, used for security, abuse prevention and rate limits. Logs are kept for 14 days.',
        '• Crash reports only if “Crash reports” is on in Settings. Product analytics only if you turn “Help improve Storyloom” on (it is off by default).',
        'What we do not collect: precise location, contacts, photos from your gallery other than the drawing you pick, advertising identifiers, or audio from your TV (Storyloom blocks microphone access on the TV).',
      ],
    },
    {
      heading: '3. How we use it',
      body: [
        '• To create, narrate, illustrate and store your family’s stories, and to run family story rooms.',
        '• To keep children safe: every idea and story is checked by automated safety filters.',
        '• To sign you in, secure accounts, prevent abuse and fix problems.',
        '• To remember helpful details between stories (for example a favourite hero) if “Family memory” is on. You can turn it off or clear it at any time.',
        '• To answer your questions and meet legal obligations.',
        'We never use personal data for advertising, never sell it, and never make decisions with legal or similarly significant effects about you by automated means.',
      ],
    },
    {
      heading: '4. How AI is used',
      body: [
        'Stories are created with AI models on Amazon Bedrock (for example Amazon Nova and Stability AI image models), narrated with Amazon Polly, and checked with Amazon Bedrock Guardrails. These services process your prompts and drawings only to produce your results. Amazon Bedrock does not use your prompts or results to train its models, and it does not share them with the model providers.',
      ],
    },
    {
      heading: '5. Legal bases (EU, UK and similar laws)',
      body: [
        '• Contract: to provide the Service you asked for.',
        '• Consent: for child profiles (given by the parent or guardian), optional analytics, crash reports and family memory. You can withdraw consent at any time in Settings.',
        '• Legitimate interests: to keep the Service safe and secure, prevent abuse and improve reliability, balanced against your rights.',
        '• Legal obligation: where the law requires us to keep or disclose information.',
        'Under India’s Digital Personal Data Protection Act, 2023, we rely on your consent (and verifiable parental consent for children) and on the legitimate uses the Act allows.',
      ],
    },
    {
      heading: '6. Who we share it with',
      body: [
        '• Amazon Web Services, which hosts Storyloom and provides the AI, storage and messaging services we use, acting on our instructions under data processing terms.',
        '• Mobile network operators, only to deliver your sign-in text message.',
        '• Authorities, when the law requires it or to protect a child or anyone else from serious harm.',
        '• A new owner, if Storyloom is ever transferred, under the same promises and with notice to you.',
        'Story rooms are private to your family: phones join only with the code on your TV, and there is no public sharing, chat with strangers or social feed.',
      ],
    },
    {
      heading: '7. Where it is stored',
      body: [
        'Storyloom’s data is stored and processed on Amazon Web Services in the United States (US East, N. Virginia). Where the law requires, we use appropriate safeguards for international transfers, such as the European Commission’s Standard Contractual Clauses.',
      ],
    },
    {
      heading: '8. How long we keep it',
      body: [
        '• Sign-in codes: 5 minutes. Codes are stored only as secure hashes and work once.',
        '• Photos of drawings: deleted automatically within 24 hours, unless you choose “Keep with the story”.',
        '• Stories and profiles: until you delete them or your account.',
        '• Service logs: 14 days. Story rooms and live connections: a few hours.',
        '• When you delete your account, we delete your data from our live systems straight away and from backups within 35 days, unless the law requires us to keep something longer.',
      ],
    },
    {
      heading: '9. How we protect it',
      body: [
        'Encryption in transit (HTTPS/TLS) and at rest; hashed phone numbers and sign-in codes; short-lived, signed links for pictures and audio; separate, least-privilege access for each part of the system; sign-in tokens you can revoke from any device; automated safety checks on all content; and continuous monitoring for errors and abuse. No system is perfectly secure, but we design Storyloom so that as little personal data as possible exists in the first place.',
      ],
    },
    {
      heading: '10. Your rights and choices',
      body: [
        'Depending on where you live, you can ask to access, correct, download, or delete your personal data, to restrict or object to some uses, and to withdraw consent. Most of this is built into the app:',
        '• Settings → Privacy & data → Download my data, Clear family memory, Delete story history.',
        '• Settings → Account → Edit family, Sign out of all devices, Delete account.',
        `You can also write to us through ${C.channel}. We answer within 30 days (or sooner if your law requires) and may need to confirm it is you. You may complain to your local data protection authority (for example the Data Protection Board of India, or a supervisory authority in the EU/UK). Residents of California and other US states have the right to know, delete and correct personal information and to opt out of its sale or sharing; we do not sell or share personal information for cross-context behavioural advertising, and we will not discriminate against you for using your rights.`,
      ],
    },
    {
      heading: '11. Children',
      body: [
        'Storyloom is designed for families with young children and follows the principles of the US Children’s Online Privacy Protection Act (COPPA), the UK Age Appropriate Design Code and India’s rules on children’s data. Please read our Children’s Privacy Notice for the details.',
      ],
    },
    {
      heading: '12. Storage on your devices',
      body: [
        'The TV app stores your sign-in and settings in the device’s secure storage. The phone companion uses your browser’s local storage to remember that you joined a story room. We do not use advertising cookies or cross-site trackers.',
      ],
    },
    {
      heading: '13. Changes to this policy',
      body: ['If we change how we use personal data in an important way, we will tell you in the app before the change takes effect and, where required, ask for your consent again.'],
    },
    {
      heading: '14. Contact',
      body: [`Privacy questions, requests or complaints: write to ${C.officer} (Grievance Officer) through ${C.channel}.`],
    },
  ],
};

export const CHILDREN: LegalDocument = {
  id: 'children',
  title: 'Children’s Privacy Notice',
  summary: [
    'Only a verified grown-up can create an account and add children.',
    'For each child we keep just a first name or nickname, an age range and an animal avatar.',
    'Drawings are deleted within 24 hours by default; no child photos, voices or locations are collected.',
    'No ads, no strangers, no public sharing. Parents can see and delete everything.',
  ],
  sections: [
    {
      heading: '1. A note for parents and guardians',
      body: [
        'This notice explains what Storyloom collects when children use it, how we use it, and your choices. It supplements our Privacy Policy. Storyloom is meant to be used by children together with a parent, guardian or other trusted grown-up.',
      ],
    },
    {
      heading: '2. Parental consent',
      body: [
        'Before any child information is collected, a grown-up must verify a mobile number with a one-time code, confirm that they are 18 or older and the child’s parent or legal guardian (or have their permission), and agree to our Terms and this notice. Only then can child profiles be added. You can review and withdraw this consent at any time.',
      ],
    },
    {
      heading: '3. What we collect from or about children',
      body: [
        '• The name or nickname and age range you enter for each child profile, and the avatar they pick.',
        '• Story ingredients a child adds with a phone during a family story: a photo of a drawing, a hero name, typed ideas (or text from the phone’s own speech-to-text), and votes.',
        '• The stories created for the family.',
        'We do not ask children for their full name, age or birthday, address, school, email, phone number, photos of themselves, voice recordings, or location, and children cannot chat with anyone.',
      ],
    },
    {
      heading: '4. How we use it',
      body: [
        'Only to create and show your family’s stories, keep them on your bookshelf, and keep the experience safe (for example, checking that a hero’s name or an idea is appropriate). We never use children’s information for advertising, profiling or selling, and we never make it public.',
      ],
    },
    {
      heading: '5. Drawings',
      body: [
        'When a child photographs a drawing, the photo is resized on the phone, stripped of hidden location data, checked for safety and turned into an illustrated hero. The original photo is deleted automatically within 24 hours unless a parent chooses to keep it with the story in Settings.',
      ],
    },
    {
      heading: '6. Sharing',
      body: [
        'Children’s information is processed only by our cloud provider (Amazon Web Services) on our behalf, and disclosed to authorities only when the law requires or to protect a child from harm.',
      ],
    },
    {
      heading: '7. Your rights as a parent',
      body: [
        '• Review your child’s profile and stories in the app at any time.',
        '• Edit or delete a child profile in Settings → Account → Edit family.',
        '• Delete stories, clear family memory, or delete the whole account and all its data.',
        '• Turn off features such as voice ideas on phones or family memory.',
        `• Ask us questions or make a request through ${C.channel}.`,
      ],
    },
    {
      heading: '8. Contact',
      body: [`${C.owner}, ${C.country}. Write to us through ${C.channel}.`],
    },
  ],
};

export const LEGAL_DOCUMENTS: Record<LegalDocument['id'], LegalDocument> = { terms: TERMS, privacy: PRIVACY, children: CHILDREN };
