"""Narrate the demo bookshelf in every language with Amazon Polly.

Uses the same narrator as the cloud agent (sentence-level synthesis with exact MP3
timing), so offline stories get the same word-by-word read-along as generated ones.

    services/agent/.venv/Scripts/python tools/audio/narrate_library.py [--only hi]

Writes apps/tv/assets/narration/<story>/<lang>/<page>.mp3 and
apps/tv/src/data/narration.generated.ts (bundled, so it works with no network).
"""
from __future__ import annotations

import argparse
import json
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "services" / "agent"))

from storyloom.narrator import narrate  # noqa: E402

STORIES = ROOT / "apps" / "tv" / "src" / "data" / "stories"
ASSETS = ROOT / "apps" / "tv" / "assets" / "narration"
OUT_TS = ROOT / "apps" / "tv" / "src" / "data" / "narration.generated.ts"

# file key -> (Polly language code, voice). English uses each story's own narrator.
LANGS = {
    "en": ("en-US", None),
    "hi": ("hi-IN", "Kajal"),
    "es": ("es-ES", "Lucia"),
    "fr": ("fr-FR", "Lea"),
    "de": ("de-DE", "Vicki"),
    "pt": ("pt-BR", "Camila"),
    "ja": ("ja-JP", "Kazuha"),
    "ar": ("ar-AE", "Hala"),
}
ENGLISH_VOICES = {
    "luna-lighthouse": ("en-US", "Ruth"),
    "tiger-roar": ("en-US", "Matthew"),
    "pip-cloud-whales": ("en-GB", "Amy"),
    "beep-garden": ("en-US", "Joanna"),
}


def job(lang: str, story: str, key: str, text: str) -> tuple[str, str, str, list, int]:
    code, voice = LANGS[lang]
    if lang == "en":
        code, voice = ENGLISH_VOICES[story]
    out = ASSETS / story / lang / f"{key}.mp3"
    audio, marks, ms = narrate(text, code, voice)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(audio)
    return lang, story, key, marks, ms


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="comma separated language keys")
    a = ap.parse_args()
    only = set(a.only.split(",")) if a.only else None

    jobs = []
    for lang in LANGS:
        if only and lang not in only:
            continue
        data = json.loads((STORIES / f"{lang}.json").read_text(encoding="utf-8"))
        for story, s in data.items():
            for key, text in s["pages"].items():
                jobs.append((lang, story, key, text))

    results = {}
    with ThreadPoolExecutor(max_workers=3) as pool:
        for lang, story, key, marks, ms in pool.map(lambda j: job(*j), jobs):
            results[(lang, story, key)] = (marks, ms)
            print(f"{lang} {story} {key}: {ms / 1000:.1f}s, {len(marks)} words", flush=True)

    # Merge with any previously generated languages so partial runs keep the rest.
    manifest_path = ASSETS / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {}
    for (lang, story, key), (marks, ms) in results.items():
        manifest.setdefault(story, {}).setdefault(lang, {})[key] = {"ms": ms, "marks": [[m["t"], m["s"], m["e"]] for m in marks]}
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")

    lines = [
        "// Generated by tools/audio/narrate_library.py. Do not edit by hand.",
        "// Amazon Polly narration for the demo bookshelf, bundled so it plays with no network.",
        "/* eslint-disable */",
        "export type Narration = { audio: number; ms: number; marks: [number, number, number][] };",
        "export const NARRATION: Record<string, Record<string, Record<string, Narration>>> = {",
    ]
    for story in sorted(manifest):
        lines.append(f"  {json.dumps(story)}: {{")
        for lang in sorted(manifest[story]):
            lines.append(f"    {json.dumps(lang)}: {{")
            for key in sorted(manifest[story][lang]):
                e = manifest[story][lang][key]
                path = f"../../assets/narration/{story}/{lang}/{key}.mp3"
                lines.append(
                    f"      {json.dumps(key)}: {{ audio: require({json.dumps(path)}), ms: {e['ms']}, marks: {json.dumps(e['marks'], separators=(',', ':'))} }},"
                )
            lines.append("    },")
        lines.append("  },")
    lines.append("};")
    OUT_TS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_TS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
